messages_en-2.txt

http://manage.dimagi.com/default.asp?156542

add wifi direct translations

---

messages_en-2.txt

Addresses some of http://manage.dimagi.com/default.asp?165957

Add missing messages

---

messages_en-2.txt

Support https://github.com/dimagi/commcare-odk/pull/406
@nickpell

Add translation for "Show Address"

---

commcare_translations.py

http://manage.dimagi.com/default.asp?178531
anyone, cc @benrudolph

escape newlines when generating translations

---

messages_en-2.txt

Auto-commit: Update translations for CommCare release 2.26

---

commcare_translations.py

@czue 
http://manage.dimagi.com/default.asp?140715

escape starting # character

---

messages_en-2.txt

@dimagi/product 2.27 Translations Ready for Review

Auto-commit: Update translations for CommCare release 2.27

---

messages_en-2.txt

fyi @dimagi/product 
@dannyroberts Picking a random HQ person to ping here, but would it make sense to assign a point-person on HQ who's responsible for merging this PR each release? Or is it fine for the mobile release manager to just self-merge?

Auto-commit: Update translations for CommCare release 2.28

---

messages_en-2.txt

In prep for the 2.29 release tomorrow

Update translations for CommCare release 2.29

---

messages_en-2.txt

@dimagi/product 2.31.0 translations!

2.31.0_release_additions

---

commcare_translations.py

add 'from __future__ import absolute_import' to all .py files

---

commcare_translations.py

python-modernize . -w -f libfuturize.fixes.fix_print_with_import

---

commcare_translations.py

python-modernize . -w -f libmodernize.fixes.fix_unicode_type

---

commcare_translations.py

use io.StringIO

---

commcare_translations.py

tests weren't passing: https://travis-ci.org/dimagi/commcare-hq/jobs/335300328

include newline

---

commcare_translations.py

python-modernize . -w --future-unicode

---

commcare_translations.py

use io.open

---

historical-translations-by-version/2.50-messages_en-2.txt

Related to this [PR](https://github.com/dimagi/commcare-core/pull/958), this [PR](https://github.com/dimagi/commcare-hq/pull/28855) and this [PR](https://github.com/dimagi/commcare-android/pull/2418).

Added new translation for "Case Claim"

---

commcare_translations.py

I've updated the code using `looseversion.LooseVersion`, which previously used `distutils.version.LooseVersion` to now use `packaging.version.Version` to more accurately reflect the intentions of the PR where this "fix" was introduced:
https://github.com/dimagi/commcare-translations/pull/37
I've also moved the relevant code to its own method so that I can call it on the tests I have planned forthcoming in this PR: https://github.com/dimagi/commcare-hq/pull/32463

Change looseversion.LooseVersion usage to packaging.version.Version

---

commcare_translations.py

simplify how we fetch major, minor, bugfix from packaging.version.Version
